package Model;
// Generated Nov 23, 2017 10:28:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbProveedor generated by hbm2java
 */
public class TbProveedor  implements java.io.Serializable {


     private Integer id;
     private String nit;
     private String razonSocial;
     private String contacto;
     private String telefono;
     private String celular;
     private String direccion;
     private byte estado;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set tbOrdenCompras = new HashSet(0);

    public TbProveedor() {
    }

	
    public TbProveedor(String nit, String razonSocial, String contacto, String telefono, String celular, String direccion, byte estado, String creadoPor, Date creadoEn) {
        this.nit = nit;
        this.razonSocial = razonSocial;
        this.contacto = contacto;
        this.telefono = telefono;
        this.celular = celular;
        this.direccion = direccion;
        this.estado = estado;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbProveedor(String nit, String razonSocial, String contacto, String telefono, String celular, String direccion, byte estado, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set tbOrdenCompras) {
       this.nit = nit;
       this.razonSocial = razonSocial;
       this.contacto = contacto;
       this.telefono = telefono;
       this.celular = celular;
       this.direccion = direccion;
       this.estado = estado;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbOrdenCompras = tbOrdenCompras;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(byte estado) {
        this.estado = estado;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set getTbOrdenCompras() {
        return this.tbOrdenCompras;
    }
    
    public void setTbOrdenCompras(Set tbOrdenCompras) {
        this.tbOrdenCompras = tbOrdenCompras;
    }




}


