package Model;
// Generated Nov 23, 2017 10:28:39 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbUbicacion generated by hbm2java
 */
public class TbUbicacion  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private String creadoPor;
     private Date creadoEn;
     private String modificadoPor;
     private Date modificadoEn;
     private Set tbMateriaPrimas = new HashSet(0);

    public TbUbicacion() {
    }

	
    public TbUbicacion(String descripcion, String creadoPor, Date creadoEn) {
        this.descripcion = descripcion;
        this.creadoPor = creadoPor;
        this.creadoEn = creadoEn;
    }
    public TbUbicacion(String descripcion, String creadoPor, Date creadoEn, String modificadoPor, Date modificadoEn, Set tbMateriaPrimas) {
       this.descripcion = descripcion;
       this.creadoPor = creadoPor;
       this.creadoEn = creadoEn;
       this.modificadoPor = modificadoPor;
       this.modificadoEn = modificadoEn;
       this.tbMateriaPrimas = tbMateriaPrimas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoEn() {
        return this.creadoEn;
    }
    
    public void setCreadoEn(Date creadoEn) {
        this.creadoEn = creadoEn;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoEn() {
        return this.modificadoEn;
    }
    
    public void setModificadoEn(Date modificadoEn) {
        this.modificadoEn = modificadoEn;
    }
    public Set getTbMateriaPrimas() {
        return this.tbMateriaPrimas;
    }
    
    public void setTbMateriaPrimas(Set tbMateriaPrimas) {
        this.tbMateriaPrimas = tbMateriaPrimas;
    }




}


